$(document).ready( function(){
  
	$.supersized({
	
		// Functionality
		slide_interval          :   8000,		// Length between transitions
		transition              :   1, 			// 0-None, 1-Fade, 2-Slide Top, 3-Slide Right, 4-Slide Bottom, 5-Slide Left, 6-Carousel Right, 7-Carousel Left
		transition_speed		:	1000,		// Speed of transition
												   
		// Components							
		slide_links				:	'false',	// Individual links for each slide (Options: false, 'num', 'name', 'blank')
		slides 					:  	[			// Slideshow http://nhackhongloi.org/images
{image : 'http://nhackhongloi.org/images/gallery/slide1.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb1.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide2.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb2.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide3.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb3.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide4.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb4.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide5.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb5.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide6.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb6.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide7.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb7.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide8.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb8.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide9.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb9.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide10.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb10.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide11.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb11.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide12.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb12.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide13.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb13.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide14.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb14.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide15.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb15.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide16.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb16.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide17.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb17.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide18.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb18.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide19.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb19.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide20.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb20.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide21.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb21.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide22.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb22.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide23.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb23.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide24.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb24.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide25.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb25.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide26.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb26.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide27.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb27.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide28.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb28.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide29.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb29.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide30.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb30.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide31.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb31.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide32.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb32.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide33.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb33.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide34.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb34.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide35.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb35.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide36.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb36.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide37.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb37.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide38.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb38.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide39.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb39.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide40.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb40.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide41.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb41.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide42.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb42.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide43.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb43.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide44.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb44.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide45.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb45.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide46.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb46.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide47.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb47.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide48.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb48.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide49.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb49.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide50.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb50.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide51.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb51.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide52.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb52.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide53.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb53.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide54.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb54.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide55.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb55.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide56.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb56.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide57.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb57.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide58.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb58.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide59.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb59.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide60.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb60.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide61.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb61.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide62.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb62.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide63.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb63.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide64.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb64.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide65.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb65.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide66.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb66.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide67.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb67.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide68.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb68.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide69.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb69.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide70.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb70.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide71.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb71.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide72.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb72.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide73.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb73.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide74.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb74.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide75.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb75.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide76.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb76.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide77.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb77.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide78.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb78.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide79.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb79.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide80.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb80.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide81.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb81.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide82.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb82.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide83.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb83.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide84.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb84.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide85.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb85.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide86.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb86.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide87.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb87.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide88.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb88.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide89.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb89.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide90.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb90.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide91.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb91.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide92.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb92.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide93.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb93.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide94.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb94.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide95.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb95.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide96.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb96.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide97.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb97.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide98.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb98.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide99.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb99.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide100.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb100.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide101.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb101.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide102.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb102.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide103.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb103.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide104.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb104.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide105.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb105.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide106.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb106.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide107.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb107.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide108.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb108.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide109.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb109.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide110.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb110.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide111.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb111.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide112.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb112.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide113.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb113.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide114.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb114.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide115.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb115.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide116.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb116.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide117.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb117.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide118.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb118.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide119.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb119.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide120.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb120.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide121.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb121.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide122.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb122.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide123.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb123.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide124.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb124.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide125.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb125.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide126.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb126.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide127.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb127.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide128.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb128.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide129.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb129.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide130.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb130.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide131.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb131.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide132.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb132.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide133.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb133.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide134.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb134.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide135.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb135.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide136.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb136.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide137.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb137.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide138.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb138.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide139.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb139.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide140.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb140.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide141.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb141.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide142.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb142.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide143.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb143.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide144.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb144.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide145.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb145.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide146.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb146.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide147.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb147.jpg', url : ''}, 
{image : 'http://nhackhongloi.org/images/gallery/slide148.jpg', thumb : 'http://nhackhongloi.org/images/gallery/thumb148.jpg', url : ''}

									]
	});
});
